### ISSUE TITLE
Why is Satin included?

### ISSUE THREAD

**Issue by pauliesnug** [Goby56/wakes#115]
It seems like satin is only referenced thrice in the entire mod, and [Satin Free Wakes](https://modrinth.com/mod/satin-free-wakes), which is just an updated fork of the last Satin-free version (v0.2.2), claims to have 3x the performance of the current 1.21.* versions. What does including Satin do for the mod exactly, how difficult would it be to separate the two?

**Comment by Goby56** [comment]
Satin makes it easier to add custom shaders and fixed some visuals bugs related to other shaders. The performance claim of 3x performance is not due to satin being removed but becuase that version of the mod doesn't have the latest wake rendering pipeline which in its infancy wasn't really performant. Version 0.3.0 should, however, have fixed this performance issue. The latest version should therefore be just as fast if not faster than Satin Free Wakes.
